version: '3.8'

services:
  mobile-api:
    build: ./app
    ports:
      - "5108:5000"
    environment:
      - FLASK_APP=server.py
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    command: python server.py
