version: '3.8'

services:
  app:
    build: ./app
    container_name: m07-binary-protections-lab
    ports:
      - "5107:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    command: python server.py
    restart: unless-stopped
