version: '3.8'

services:
  api06-app:
    build: ./app
    ports:
      - "5006:5000"
    environment:
      - FLASK_ENV=development
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./app:/app

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
