version: '3.8'

services:
  privacy-controls-app:
    build: ./app
    container_name: m06-privacy-controls-lab
    ports:
      - "5106:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    command: python server.py
    restart: unless-stopped
