version: '3.8'

services:
  api:
    build: .
    container_name: api02-weak-auth-lab
    ports:
      - "5002:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./app:/app
    restart: unless-stopped
