version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "5109:5109"
    volumes:
      - ./app:/app
    environment:
      - FLASK_ENV=development
    container_name: m09-insecure-storage-lab
