version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: ../../../../../labs/base/Dockerfile
    ports:
      - "5024:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=0
    volumes:
      - ./app:/app
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge
