version: '3.8'

services:
  supply-chain-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m02-supply-chain-lab
    ports:
      - "7002:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=server.py
    volumes:
      - ./app:/app
    networks:
      - supply-chain-network
    restart: unless-stopped

networks:
  supply-chain-network:
    driver: bridge
